version: "2"

volumes:
  mongo_data:
  mongo_config:

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongodb:27017"
